version: "3.7"

services:
  nginx-proxy:
    build:
      context: ../backend/proxy
      dockerfile: nginx.Dockerfile
    restart: always
    volumes:
      - ../backend/proxy/config/default.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on: 
      - app-server

  app-server:
    build: 
      context: ../backend/app
      dockerfile: app.Dockerfile
    container_name: app-server
    restart: always
    volumes:
      - ../backend/app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis-server

  redis-server:
    build:
      context: ../backend/redis
      dockerfile: redis.Dockerfile
    restart: always
    container_name: redis-server
